const CATEGORIES = [
  { id: undefined, name: 'All' },
  { id: 1, name: '🍆 Colorful Harvest' },
  { id: 2, name: '🥕 Roots & Tubers' },
  { id: 3, name: '🌱 Aromatics & Herbs' },
  { id: 4, name: '🌿 Leafy & Fresh' },
  { id: 5, name: '🥦 Crucifers & Stalks' },
  { id: 6, name: '🌿 Legumes' },
];

const PRODUCTS = [
  {
    id: 11,
    name: 'Tomato',
    category: 1,
    price: 55,
    unit: 'kg',
    quantity: 1,
    image: 'tomato.jpg',
  },
  {
    id: 12,
    name: 'Red Bell Pepper',
    category: 1,
    price: 35,
    unit: 'piece',
    quantity: 1,
    image: 'bellpepper-red.jpg',
  },
  {
    id: 13,
    name: 'Yellow Bell Pepper',
    category: 1,
    price: 35,
    unit: 'piece',
    quantity: 1,
    image: 'bellpepper-yellow.jpg',
  },
  {
    id: 14,
    name: 'Green Bell Pepper',
    category: 1,
    price: 35,
    unit: 'piece',
    quantity: 1,
    image: 'bellpepper-green.jpg',
  },
  {
    id: 15,
    name: 'Eggplant',
    category: 1,
    price: 50,
    unit: 'kg',
    quantity: 1,
    image: 'eggplant.jpg',
  },
  {
    id: 16,
    name: 'Zucchini',
    category: 1,
    price: 60,
    unit: 'kg',
    quantity: 1,
    image: 'zucchini.jpg',
  },
  {
    id: 17,
    name: 'Pumpkin',
    category: 1,
    price: 80,
    unit: 'piece',
    quantity: 1,
    image: 'pumpkin.jpg',
  },
  {
    id: 18,
    name: 'Chili Pepper',
    category: 1,
    price: 70,
    unit: 'gr',
    quantity: 500,
    image: 'chili-pepper.jpg',
  },
  {
    id: 19,
    name: 'Okra',
    category: 1,
    price: 70,
    unit: 'kg',
    quantity: 1,
    image: 'okra.jpg',
  },

  {
    id: 22,
    name: 'Potato',
    category: 2,
    price: 30,
    unit: 'kg',
    quantity: 1,
    image: 'potato.jpg',
  },
  {
    id: 21,
    name: 'Carrot',
    category: 2,
    price: 45,
    unit: 'kg',
    quantity: 1,
    image: 'carrot.jpg',
  },
  {
    id: 23,
    name: 'Sweet Potato',
    category: 2,
    price: 50,
    unit: 'kg',
    quantity: 1,
    image: 'sweet-potato.jpg',
  },
  {
    id: 24,
    name: 'Radish',
    category: 2,
    price: 35,
    unit: 'gr',
    quantity: 500,
    image: 'radish.jpg',
  },
  {
    id: 25,
    name: 'Beetroot',
    category: 2,
    price: 55,
    unit: 'kg',
    quantity: 1,
    image: 'beetroot.jpg',
  },
  {
    id: 26,
    name: 'Taro',
    category: 2,
    price: 40,
    unit: 'kg',
    quantity: 1,
    image: 'taro.jpg',
  },
  {
    id: 27,
    name: 'Cassava',
    category: 2,
    price: 40,
    unit: 'kg',
    quantity: 1,
    image: 'cassava.jpg',
  },

  {
    id: 31,
    name: 'Onion',
    category: 3,
    price: 35,
    unit: 'kg',
    quantity: 1,
    image: 'onion-white.jpg',
  },
  {
    id: 33,
    name: 'Red Onion',
    category: 3,
    price: 40,
    unit: 'kg',
    quantity: 1,
    image: 'onion-red.jpg',
  },
  {
    id: 32,
    name: 'Garlic',
    category: 3,
    price: 80,
    unit: 'kg',
    quantity: 1,
    image: 'garlic.jpg',
  },
  {
    id: 34,
    name: 'Basil',
    category: 3,
    price: 100,
    unit: 'gr',
    quantity: 100,
    image: 'basil.jpg',
  },
  {
    id: 35,
    name: 'Cilantro',
    category: 3,
    price: 40,
    unit: 'gr',
    quantity: 250,
    image: 'cilantro.jpg',
  },

  {
    id: 42,
    name: 'Lettuce',
    category: 4,
    price: 40,
    unit: 'piece',
    quantity: 1,
    image: 'lettuce.jpg',
  },
  {
    id: 41,
    name: 'Spinach',
    category: 4,
    price: 50,
    unit: 'kg',
    quantity: 1,
    image: 'spinach.jpg',
  },
  {
    id: 44,
    name: 'Cabbage',
    category: 4,
    price: 55,
    unit: 'piece',
    quantity: 1,
    image: 'cabbage.jpg',
  },
  {
    id: 43,
    name: 'Kale',
    category: 4,
    price: 60,
    unit: 'gr',
    quantity: 500,
    image: 'kale.jpg',
  },
  {
    id: 45,
    name: 'Parsley',
    category: 4,
    price: 30,
    unit: 'gr',
    quantity: 250,
    image: 'parsley.jpg',
  },
  {
    id: 46,
    name: 'Morning Glory',
    category: 4,
    price: 35,
    unit: 'gr',
    quantity: 250,
    image: 'morning-glory.jpg',
  },

  {
    id: 51,
    name: 'Broccoli',
    category: 5,
    price: 70,
    unit: 'gr',
    quantity: 500,
    image: 'broccoli.jpg',
  },
  {
    id: 52,
    name: 'Cauliflower',
    category: 5,
    price: 60,
    unit: 'piece',
    quantity: 1,
    image: 'cauliflower.jpg',
  },
  {
    id: 55,
    name: 'Celery',
    category: 5,
    price: 50,
    unit: 'gr',
    quantity: 500,
    image: 'celery.jpg',
  },
  {
    id: 53,
    name: 'Asparagus',
    category: 5,
    price: 120,
    unit: 'gr',
    quantity: 500,
    image: 'asparagus.jpg',
  },
  {
    id: 54,
    name: 'Brussels Sprouts',
    category: 5,
    price: 90,
    unit: 'gr',
    quantity: 500,
    image: 'brussels-sprouts.jpg',
  },

  {
    id: 61,
    name: 'Green Beans',
    category: 6,
    price: 55,
    unit: 'kg',
    quantity: 1,
    image: 'green-beans.jpg',
  },
  {
    id: 62,
    name: 'Peas',
    category: 6,
    price: 60,
    unit: 'kg',
    quantity: 1,
    image: 'peas.jpg',
  },
  {
    id: 63,
    name: 'Lentils',
    category: 6,
    price: 45,
    unit: 'kg',
    quantity: 1,
    image: 'lentils.jpg',
  },
  {
    id: 64,
    name: 'Chickpeas',
    category: 6,
    price: 50,
    unit: 'kg',
    quantity: 1,
    image: 'chickpeas.jpg',
  },
  {
    id: 65,
    name: 'Edamame',
    category: 6,
    price: 80,
    unit: 'gr',
    quantity: 500,
    image: 'edamame.jpg',
  },
];
